def post_visits_data(conn, api_url)
    
    start_time = Time.parse('05/08/2024 14:30:00') 
    end_time = start_time + 15 * 60

    visit_data = [
        { 
            result: 303131,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0102',
            longitude: -103.3618535,
        },
        { 
            result: 303131,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0109',
            longitude: -103.3618535,
        },
        { 
            result: 303131,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0087',
            longitude: -103.3618535,
        },
        { 
            result: 303131,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0100',
            longitude: -103.3618535,
        },
        { 
            result: 303131,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0108',
            longitude: -103.3618535,
        },
        { 
            result: 303131,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0115',
            longitude: -103.3618535,
        },
        { 
            result: 303131,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0105',
            longitude: -103.3618535,
        },
        { 
            result: 303131,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0076',
            longitude: -103.3618535,
        },
        { 
            result: 303131,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0069',
            longitude: -103.3618535,
        },
        { 
            result: 303131,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0111',
            longitude: -103.3618535,
        },
        { 
            result: 303132,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0106',
            longitude: -103.3618535,
        },
        { 
            result: 303135,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0090',
            longitude: -103.3618535,
        },
        { 
            result: 303135,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0094',
            longitude: -103.3618535,
        },
        { 
            result: 303135,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0091',
            longitude: -103.3618535,
        },
        { 
            result: 303133,
            createdBy: 87852,
            latitude: 20.6760381,
            start: start_time.strftime('%d/%m/%Y %H:%M:%S'),
            accuracy: 30,
            calendarEvent: 1,
            comment: 'Sin comentarios',
            end: end_time.strftime('%d/%m/%Y %H:%M:%S'),
            customer: 'CTE0107',
            longitude: -103.3618535,
        },
    ]

    visit_data.each do |data|
        post_data(conn, "#{api_url}/visit", data)
        sleep(1)
    end
end